afternoon_work/config/routes.rb
AfternoonWork::Application.routes.draw do
  resources :games
  resources :consoles

  root :to => 'games#index'

end

afternoon_work/app/models/console.rb
class Console < ActiveRecord::Base
  belongs_to :game
end

afternoon_work/app/models/game.rb
class Game < ActiveRecord::Base
  has_many :consoles
end

afternoon_work/app/controllers/consoles_controller.rb
class ConsolesController <ApplicationController

  def index
    @consoles = Console.all
  end

  def show
    @console = Console.find(params[:id])
  end

  def new
    @console = Console.new
    @console.game_id = :game_id
  end

  def create
    debugger
    @console = Console.new(params[:console])
      current_game = :game_id
      @console.game_id = current_game
    if @console.save
      redirect_to @console
    else
      render "new"
    end
  end

  def edit 
    @console = Console.find(params[:id])
  end

  def update
    @console = Console.find(params[:id]) 
    if @console.update_attributes(params[:console])
      redirect_to @console
    else
      render "edit"
    end
  end

  def destroy
    @console = Console.find(params[:id])
    @console.destroy
    redirect_to consoles_url
  end


end

afternoon_work/app/controllers/games_controller.rb
class GamesController <ApplicationController

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(params[:game])
    if @game.save
      redirect_to @game
    else
      render "new"
    end
  end

  def edit 
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id]) 
    if @game.update_attributes(params[:game])
      redirect_to @game
    else
      render "edit"
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_url
  end


end

afternoon_work/app/views/consoles/create.html.erb
<%=params%>

afternoon_work/app/views/consoles/edit.html.erb
<h1>Editing User</h1>

<%= form_for(@console) do |f| %>
 <div class="field">
    <%=f.label "Console Name"%>
    <br> 
    <%=f.text_field :console_name %>
  </div>

  <div class="actions">
    <%=f.submit%>
  </div>

<%end%> 

<%=link_to "Show", @console %>
<%=link_to "Back", games_path%>

afternoon_work/app/views/consoles/index.html.erb
<h1>Consoles</h1>

<ul>
<% @consoles.each do |t| %>
  <li><%=t.console_name%></li>
  
  <p><%= link_to('Edit', "consoles/#{t.id}/edit")%></p>
  <p>
    <%= button_to "Delete", t, :method => :delete, :data => { :confirm => "Are you sure"} %>
  </p>
  <%end%>
</ul>

afternoon_work/app/views/consoles/new.html.erb
<%= form_for(@console) do |f| %>
 <div class="field">
    <%=f.label "Console Name"%>
    <br> 
    <%=f.text_field :console_name %>
    <%=f.hidden_field :game_id, :value => params[:id] %>
  </div>

  <div class="actions">
    <%=f.submit%>
  </div>

<%end%> 

afternoon_work/app/views/consoles/show.html.erb
<%=@console.console_name%>

<p><%=link_to("Back", consoles_path)%></p>

afternoon_work/app/views/games/create.html.erb
<%=params%>

afternoon_work/app/views/games/edit.html.erb
<h1>Editing User</h1>

<%= form_for(@game) do |f| %>
 <div class="field">
    <%=f.label :name%>
    <br> 
    <%=f.text_field :name %>
  </div>

  <div class="actions">
    <%=f.submit%>
  </div>

<%end%> 

<%=link_to "Show", @game %>
<%=link_to "Back", games_path%>

afternoon_work/app/views/games/index.html.erb
<h1>Games</h1>

<ul>
<% @games.each do |t| %>
  <li><%=t.name%></li>
  
  <p><%=link_to('Add Console', new_console_path(:id => t.id))%></p>

  <p><%= link_to('Edit', "games/#{t.id}/edit")%></p>

  <p>
    <%= button_to "Delete", t, :method => :delete, :data => { :confirm => "Are you sure"} %>
  </p>
  <%end%>
</ul>

afternoon_work/app/views/games/new.html.erb
<%= form_for(@game) do |f| %>
 <div class="field">
    <%=f.label :name%>
    <br> 
    <%=f.text_field :name %>
  </div>

  <div class="actions">
    <%=f.submit%>
  </div>

<%end%> 

afternoon_work/app/views/games/show.html.erb
<%=@game.name%>

<p><%=link_to("Back", games_path)%></p>

afternoon_work/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AfternoonWork</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>